// <auto-generated />
using Employee.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230113093916_Initial_Seed")]
    partial class Initial_Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.Core.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Department = "HR",
                            Email = "rvd.kashyap@gmail.com",
                            FirstName = "Rovid",
                            LastName = "Kashyap",
                            Mobile = "9760828296"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Department = "IT",
                            Email = "dhr.varun@gmail.com",
                            FirstName = "Dhirendra",
                            LastName = "Varun",
                            Mobile = "8909371977"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Department = "Administration",
                            Email = "chetan.singh@gmail.com",
                            FirstName = "Shobit",
                            LastName = "Goyal",
                            Mobile = "9045326030"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Department = "HR",
                            Email = "lalit.gautam@gmail.com",
                            FirstName = "Lalit",
                            LastName = "Gautam",
                            Mobile = "9456201030"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Department = "Sales",
                            Email = "ruchi.cute@gmail.com",
                            FirstName = "Ruchi",
                            LastName = "Khandelwal",
                            Mobile = "9965112200"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
